In [33]:
import pandas as pd

In [34]:
stream_pd = pd.read_json('/content/StreamingHistory_music_1.json')

In [35]:
stream_pd.head()

,endTime,artistName,trackName,msPlayed
0,2025-11-13 17:40,Nathaniel Bassey,Hallelujah Eh,981
1,2025-11-13 17:41,Katy Nichole,In Jesus Name (God Of Possible),1856
2,2025-11-13 17:41,BisiManuel,Ijinle Ninu Ijinle,2283
3,2025-11-13 17:41,Sinach,More,981
4,2025-11-13 17:41,Hillsong Chapel,It Is Well With My Soul,1429

In [36]:
stream_pd.shape

(4524, 4)

In [37]:
stream_pd.isnull().sum()

endTime       0
artistName    0
trackName     0
msPlayed      0
dtype: int64

In [38]:
stream_pd.dtypes

endTime       object
artistName    object
trackName     object
msPlayed       int64
dtype: object

**Converting EndTime to DateTime Format & Extracting Specific Components**

In [39]:
stream_pd['endTime'] = pd.to_datetime(stream_pd['endTime'])

In [40]:
stream_pd['endTime']

0      2025-11-13 17:40:00
1      2025-11-13 17:41:00
2      2025-11-13 17:41:00
3      2025-11-13 17:41:00
4      2025-11-13 17:41:00
               ...
4519   2026-02-11 20:10:00
4520   2026-02-11 20:10:00
4521   2026-02-11 20:10:00
4522   2026-02-11 20:10:00
4523   2026-02-13 23:19:00
Name: endTime, Length: 4524, dtype: datetime64[ns]

In [41]:
stream_pd.dtypes

endTime       datetime64[ns]
artistName            object
trackName             object
msPlayed               int64
dtype: object

In [42]:
stream_pd['date']  = stream_pd['endTime'].dt.date
stream_pd['hour']  = stream_pd['endTime'].dt.hour
stream_pd['weekday'] = stream_pd['endTime'].dt.day_name()
stream_pd['month']   = stream_pd['endTime'].dt.month_name()


print(stream_pd[['endTime', 'date', 'hour', 'weekday', 'month']].head())

              endTime        date  hour   weekday     month
0 2025-11-13 17:40:00  2025-11-13    17  Thursday  November
1 2025-11-13 17:41:00  2025-11-13    17  Thursday  November
2 2025-11-13 17:41:00  2025-11-13    17  Thursday  November
3 2025-11-13 17:41:00  2025-11-13    17  Thursday  November
4 2025-11-13 17:41:00  2025-11-13    17  Thursday  November

**Identifying Skipped Songs**

In [43]:
stream_pd['minutes_played'] = (stream_pd['msPlayed']/60000).round(2)

In [44]:
stream_pd['minutes_played'].head()

0    0.02
1    0.03
2    0.04
3    0.02
4    0.02
Name: minutes_played, dtype: float64

In [45]:
stream_pd ['skipped_songs'] = stream_pd['msPlayed'] < 30000

In [48]:
stream_pd ['skipped_songs'].head(100)

0      True
1      True
2      True
3      True
4      True
      ...
95    False
96    False
97    False
98    False
99    False
Name: skipped_songs, Length: 100, dtype: bool

In [52]:
from google.colab import files
stream_pd.to_csv('spotify_clean.csv', index=False)

files.download('spotify_clean.csv')
print("Exported successfully")

Exported successfully

In [56]:
stream_pd[stream_pd['month'] == 'February']

,endTime,artistName,trackName,msPlayed,date,hour,weekday,month,minutes_played,skipped_songs
3303,2026-02-01 15:19:00,ALIA LARA,Praising You,1650,2026-02-01,15,Sunday,February,0.03,True
3304,2026-02-01 15:22:00,Grace Tena,His Words,770,2026-02-01,15,Sunday,February,0.01,True
3305,2026-02-01 15:22:00,Gatton,Nothing Else,940,2026-02-01,15,Sunday,February,0.02,True
3306,2026-02-01 15:22:00,OBED,Come Like A Rushing Wind,161470,2026-02-01,15,Sunday,February,2.69,False
3307,2026-02-01 15:22:00,sxxnt.,Another In the Fire,600,2026-02-01,15,Sunday,February,0.01,True
...,...,...,...,...,...,...,...,...,...,...
4519,2026-02-11 20:10:00,Tauren Wells,Take It All Back,1030,2026-02-11,20,Wednesday,February,0.02,True
4520,2026-02-11 20:10:00,The Spirituals,Wade In The Water - Live,820,2026-02-11,20,Wednesday,February,0.01,True
4521,2026-02-11 20:10:00,the King will come,yet (don't give up),1070,2026-02-11,20,Wednesday,February,0.02,True
4522,2026-02-11 20:10:00,Chandler Moore,Omemma - Live,1390,2026-02-11,20,Wednesday,February,0.02,True
4523,2026-02-13 23:19:00,Chandler Moore,Omemma - Live,592000,2026-02-13,23,Friday,February,9.87,False